name: CI

on:
  push:
      branches:
        - production
      paths:
        - 'index.html'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Copy index to S3
      uses: tpaschalis/s3-cp-action@v0.2.0
