name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: npm install
    - name: Patch presite
      run: node scripts/patch-presite.js
    - name: Build
      run: npm run build
    - name: Add prerender hosts
      run: |
        sudo echo "127.0.0.1 dist.local" | sudo tee -a /etc/hosts
        sudo echo "127.0.0.1 content.local" | sudo tee -a /etc/hosts
    - name: Prerender
      run: npm run prerender
    - name: Postprocess prerendered
      run: npm run postprocess-prerendered -- "https://pfiers.net"
    - name: Deploy
      uses: s0/git-publish-subdir-action@v2.4.0
      env:
        REPO: self
        BRANCH: build
        FOLDER: prerendered
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
